name: Update requirements.txt
on: push
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install pipreqs

      - name: Run pipreqs
        run: |
          pipreqs --force

      - name: Commit changes
        run: |
        if [ ! -f requirements.txt ]; then
          echo 'requirements.txt does not exist'
          exit 0
        fi

          if git diff --name-only | grep 'requirements.txt' > /dev/null; then
            echo 'requirements.txt updated'
            git config --global user.name 'Levi V'
            git config --global user.email 'levi@redhat.com'
            git commit -am "Automated update to requirements.txt"
            git push
          fi

          if [ -s requirements.txt ] ; then
            echo 'requirements.txt is empty'
            rm requirements.txt
            git config --global user.name 'Levi V'
            git config --global user.email 'levi@redhat.com'
            git commit -am "Automated removal of requirements.txt"
            git push
          fi
