name: Update requirements.txt
on: push
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install pipreqs

      - name: Run pipreqs
        run: |
          pipreqs --force

      - name: Commit changes
        run: |
          if git diff --name-only | grep 'requirements.txt' > /dev/null; then
              echo 'requirements.txt updated'
          fi

          if [[ -f requirements.txt && -s requirements.txt ]] ; then
            echo 'requirements.txt is not empty'
          else
            echo 'requirements.txt is empty'
            requirements.txt
            echo 'requirements.txt removed'
          fi

          if [ -n "$(git status --porcelain)" ]; then
            echo 'changes detected'
            git config --global user.name 'Levi V'
            git config --global user.email 'levi@redhat.com'
            git commit -am "Automated update to the requirements.txt"
            git push
            echo 'changes commited'
          fi
